---
  - name: Install pre-requisites to setup bench
    hosts: localhost
    become: yes
    become_user: root
    vars:
      - mysql_conf_tpl: ../templates/mariadb_config.cnf
      - nginx_conf_file: ../templates/nginx.conf
      - mysql_secure_installation: True
    roles:
      - mariadb
      - nginx
      - wkhtmltopdf
    tasks:
      - name: Install the 'Development tools' package group (Redhat)
        yum: name="@Development tools" state=present
        when: ansible_os_family == 'RedHat'
      - name: Install redis # For Redhat
        yum: name={{ item }} state=present
        with_items:
            - redis
            - nodejs
            - npm
        when: ansible_os_family == 'RedHat'
      - name: Install redis # For Debian
        apt: pkg={{ item }} state=present force=yes
        with_items:
            - redis-server
            - nodejs
            - npm
        when: ansible_os_family == 'Debian'
