---
  - name: Set root Password
    mysql_user:
      name=root
      host={{ item }}
      password={{ mysql_root_password }}
      state=present
      login_user=root
    with_items:
      - localhost
    when: mysql_root_password is defined

  - name: Add configuration
    template: src={{ mysql_config_template }} dest={{ mysql_conf_dir }}/frappe.cnf owner=root mode=0644
    notify: restart mysql
    become: yes
    become_method: sudo
