---
  - name: Check if ERPNext App exists
    stat: path="{{ bench_path }}/apps/erpnext"
    register: app

  - name: get erpnext
    command: bench get-app erpnext https://github.com/frappe/erpnext --branch {{ branch }}
    args:
      creates: "{{ bench_path }}/apps/erpnext"
      chdir: "{{ bench_path }}"
    when: not app.stat.exists

  - name: Check whether a site called site1.local exists
    stat: path="{{ bench_path }}/sites/site1.local"
    register: site_folder

  - name: Link mysql.sock file for MariaDB
    file:
      src: "/var/lib/mysql/mysql.sock"
      dest: "/var/run/mysqld/mysqld.sock"
      state: link
    become: yes
    become_user: root

  - name: Link mysql.pid file for MariaDB
    file:
      src: "/var/lib/mysql/mysql.pid"
      dest: "/var/run/mysqld/mysqld.pid"
      state: link
    become: yes
    become_user: root

  - name: create a new default site 
    command: bench new-site site1.local --admin-password {{ admin_password }} --mariadb-root-password {{ mysql_root_password }}
    args:
      chdir: "{{ bench_path }}"
    when: not site_folder.stat.exists

  - name: install erpnext to default site
    command: bench --site site1.local install-app erpnext
    args:
      chdir: "{{ bench_path }}"

