---

     - name: "easy_install suprevisor CentOS 6"
       command: easy_install supervisor

     - shell: curl -Ss https://raw.githubusercontent.com/pdvyas/supervisor-initscripts/master/redhat-init-jkoppe > /etc/init.d/supervisord

     - shell: curl -Ss https://raw.githubusercontent.com/pdvyas/supervisor-initscripts/master/redhat-sysconfig-jkoppe > /etc/sysconfig/supervisord

     - shell: curl -Ss https://raw.githubusercontent.com/pdvyas/supervisor-initscripts/master/supervisord.conf > /etc/supervisord.conf

     - shell: mkdir /etc/supervisor.d

     - shell: chmod +x /etc/init.d/supervisord

     - name: "Start supervisord service CentOS6"
       shell: service supervisord start || true
